export const LANDING_BUILDINGS_MOCK = [
  {
    id: "1",
    name: "Home Inclusive Amengual",
    commune: "Estación Central",
    price: 210000,
    image: "/images/amengual-1.jpg",
    rating: 4.8,
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    available: true,
  },
  {
    id: "2",
    name: "Residencial Las Condes",
    commune: "Las Condes",
    price: 850000,
    image: "/images/las-condes-1.jpg",
    rating: 4.9,
    bedrooms: 2,
    bathrooms: 2,
    area: 75,
    available: true,
  },
  {
    id: "3",
    name: "Loft Providencia",
    commune: "Providencia",
    price: 650000,
    image: "/images/providencia-1.jpg",
    rating: 4.7,
    bedrooms: 1,
    bathrooms: 1,
    area: 50,
    available: true,
  },
];

export const HOME_AMENGUAL_EXTENDED = {
  id: "1",
  name: "Home Inclusive Amengual",
  commune: "Estación Central",
  address: "Amengual 1234, Estación Central",
  description: "Moderno edificio con excelente conectividad y amenidades",
  price: 210000,
  images: [
    "/images/amengual-1.jpg",
    "/images/amengual-2.jpg",
    "/images/amengual-3.jpg",
  ],
  amenities: [
    "WiFi",
    "Estacionamiento",
    "Gimnasio",
    "Piscina",
    "Sala de eventos",
  ],
  units: [
    {
      id: "1-1",
      type: "1D1B",
      price: 210000,
      area: 45,
      available: true,
    },
    {
      id: "1-2",
      type: "2D1B",
      price: 280000,
      area: 60,
      available: true,
    },
  ],
  rating: 4.8,
  reviews: 127,
  available: true,
};
